### ISSUE TITLE
invisible mouse in desktop

### ISSUE THREAD

**Issue by notpabloescobar** [ChimeraOS/chimeraos#703] opened 2023-07-24 06:14 UTC
mouse pointer is invisible on desktop when using steam desktop configuration for gamepad. so far ive been able to replicate this issue on steamdeck and AOKZOE A1. issue persists on deck with touch pad mouse

**Comment by alkazar** [comment] 2023-07-25 11:58
Duplicate of #700

**Closed by alkazar** 2023-07-25 11:58 UTC
