### ISSUE TITLE
Stuck after Syslinux Copyright message with a blank cursor

### ISSUE THREAD

**Issue by patrick-13x** [ChimeraOS/chimeraos#604] opened 2023-04-25 10:31 UTC
Hi,
I'm trying to run ChimeraOS but after the installation is done and I reboot the computer get stuck after Syslinux Copyright message with a blank cursor. 
If I press alt+ctrl+F2 I can acces a terminal for a few seconds and then it goes back to the blank cursor. 
Any help is appreciated! 
Thanks.

**Comment by alkazar** [comment] 2023-04-25 11:52
What GPU do you have. It is likely not supported. Please check the requirements on the download page:
https://chimeraos.org/download/

**Comment by patrick-13x** [comment] 2023-04-25 16:43
Thanks for your reply. 
I'm using integrated graphics on old hardware. 
I'm going to try with Nvidia GPU soon. 

I'll post updates. 

Thanks.

**Comment by ttimaizumi** [comment] 2023-04-26 19:22
will this work for a mobile NVIDIA GTX 650M? I'm trying to install in an old alienware alpha

**Comment by pastaq** [comment] 2023-04-28 03:28
Nvidia has very bad support for Wayland. It only works on 10 series and above and even then the experience is quite bad in most cases. It works best if there is an iGPU with your processor to render the UI while using the Nvidia GPU to render games. This should happen automatically with dxvk if you have an iGPU and an Nvidia GPU.

**Comment by ruineka** [comment] 2023-04-28 04:17
> Nvidia has very bad support for Wayland. It only works on 10 series and above and even then the experience is quite bad in most cases. It works best if there is an iGPU with your processor to render the UI while using the Nvidia GPU to render games. This should happen automatically with dxvk if you have an iGPU and an Nvidia GPU.

To do this your motherboard needs to support having the iGPU and dedicated GPU being enabled at the same time and you'll be plugging into the motherboard and not the GPU.

**Comment by Samsagax** [comment] 2023-07-04 12:11
Closing as the issue is related to old hardware we don´t really support

**Closed by Samsagax** 2023-07-04 12:11 UTC
