### ISSUE TITLE
Missing unicode font/text in update progress?

### ISSUE THREAD

**Issue by Tennyleaz** [ChimeraOS/chimeraos#183] opened 2021-01-20 12:25 UTC
I'm using gamer os 22, Steam 1608507519, in Traditional Chinese locale.
The updating screen doesn't show correct text:

![20210120_200401](https://user-images.githubusercontent.com/7089271/105174488-997b1a80-5b5d-11eb-8f4e-4397806e4dbe.jpg)

Maybe it's a missing font?

**Comment by alkazar** [comment] 2021-01-21 01:53
GamerOS does include `wqy-zenhei`.

Does this problem only happen on this update screen or everywhere in Steam as well?

Also, is this the initial Steam update/install when you first started up GamerOS?

**Comment by Tennyleaz** [comment] 2021-01-21 02:02
This problem only occurs in this update screen, in other places unicode text shows just fine.

This is not the initial install. 
I installed gamer os 20 in English locale back then, updating to gamer os 21 and to 22. 
This problem I think had occurred 2~3 times during steam update.

**Comment by alkazar** [comment] 2021-01-21 02:10
This screen required some work to get even the English text working. I believe it looks for fonts at a path hard coded for Ubuntu. It could be something similar for other languages as well.

What language setting do you have Steam set to exactly?

**Comment by Tennyleaz** [comment] 2021-01-21 02:14
> What language setting do you have Steam set to exactly?

I installed gamer os in English locale. After initial installation I changed my Steam locale to Traditional Chinese.

**Comment by sharkwouter** [comment] 2021-01-21 08:36
Steam should make use of the fonts found in the wqy-zenhei package for this. Not sure why it isn't working. Is it just during the update or after as well?

**Comment by Tennyleaz** [comment] 2021-01-21 09:21
> Is it just during the update or after as well?

The problem is just during this update UI.

**Comment by sharkwouter** [comment] 2021-01-21 09:28
Looks like a Steam bug then

**Comment by deathxxx123** [comment] 2022-03-23 20:48
This problem is happen when you use Bulgarian language too.
In Ubuntu distros all are good. With Arch distros all have missing fonts.
To reproduce, just change language to Bulgarian and then try update steam.
Its not steam client bug, but something with distros with different path for fonts or just missing.

**Comment by sharkwouter** [comment] 2022-03-24 08:25
This is still a problem? Damn. So on Ubuntu the wqy-zenhei font files are in ``/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc`` and on Arch they are at ``/usr/share/fonts/wenquanyi/wqy-zenhei/wqy-zenhei.ttc``.

Could you try the following on the command line/ssh and see if that fixes it:
```
sudo mkdir -p /usr/share/fonts/truetype/wqy
sudo ln -s /usr/share/fonts/wenquanyi/wqy-zenhei/wqy-zenhei.ttc /usr/share/fonts/truetype/wqy/wqy-zenhei.ttc
```
If it asks for a password, I think the default password is gamer unless it was changed.

**Comment by alkazar** [comment] 2022-08-12 13:07
Looks like this might be fixed in the latest Steam client beta according to these release notes:

https://www.gamingonlinux.com/2022/08/steam-deck-got-a-few-beta-updates-recently-so-heres-whats-new/

**Closed** 2022-09-21 00:38 UTC
