### ISSUE TITLE
Pairing gulikit controllers causes nonstop vibration

### ISSUE THREAD

**Issue by byronpc** [ChimeraOS/chimeraos#443] opened 2022-12-04 07:31 UTC
the controller buttons work but it doesn't stop vibrating. using unstable 38

**Comment by Samsagax** [comment] 2022-12-27 12:26
Seems duplicate of #420
Does it still happen?

**Comment by sabatmonk** [comment] 2023-02-04 19:42
In my case, it is still doing it
(latest release)

**Closed** 2023-02-07 16:02 UTC
Labels: duplicate
