### ISSUE TITLE
How to install Tidal-Hifi on ChimeraOS?

### ISSUE THREAD

**Issue by peterge1998** [ChimeraOS/chimeraos#498] opened 2023-01-30 13:16 UTC
I would like to install https://github.com/Mastermindzh/tidal-hifi.
I can install this by running `flatpak install flathub com.mastermindzh.tidal-hifi`, but when I add it as non-steam programm and return to gaming mode it does not show up where the other installed flatpaks are.

Does this need to be added to chimera's webui?

**Comment by alkazar** [comment] 2023-01-30 13:29
Please install flatpaks using the Chimera web app.

Currently, using shortcuts installed through the web app and shortcuts installed through other means do not mix.

Closing as a duplicate of chimeraos/chimera#239

**Closed by alkazar** 2023-01-30 13:29 UTC

**Comment by peterge1998** [comment] 2023-01-30 14:22
Okay, did not know this. Are there any plans to make the "show all apps" for the flathub website from chimera searchable?

**Comment by peterge1998** [comment] 2023-01-30 14:35
Oh, its possible to just add the package name to http://<hostnem>/library/flathub/edit/,
com.mastermindzh.tidal-hifi for me
