### ISSUE TITLE
Unable to use steam shortcuts with xbox one controller

### ISSUE THREAD

**Issue by frzifus** [ChimeraOS/chimeraos#459] opened 2022-12-19 18:37 UTC
Using a ps4 controller everything works fine. But pressing Steam (xbox key) + :arrow_down: no keyboard shows up. All the other shortcuts also do not work.

its connected via bluetooth.

**Comment by uejji** [comment] 2022-12-20 00:44
I've noticed this, too (running 37 1877cb7).  What seems to work for me is to tap the guide button, and then after a very short delay tap the second button.  For instance, guide (tap, don't hold), wait a very small moment, A to access the quick settings panel, or guide, wait a very small moment, X to access the OSK.  I'm sure this isn't the intended behavior.

**Comment by alkazar** [comment] 2022-12-20 02:19
To bring up the virtual keyboard the combo is guide + X.

**Comment by pastaq** [comment] 2022-12-20 05:31
Duplicate of #457

**Comment by frzifus** [comment] 2022-12-25 14:35
@alkazar you are right. Thats the key i had in mind.

Using the workaround mentioned in #457 iam able to open the fsr menu. But it doesnt work with the on screen keyboard. :/

**Comment by uejji** [comment] 2022-12-25 15:12
> But it doesnt work with the on screen keyboard. :/

Try opening the OSK while running a game or app.  It works for me then.

**Comment by Samsagax** [comment] 2023-02-07 16:10
Seems to be working with latest steam client updates. Could you confirm please?

**Comment by frzifus** [comment] 2023-02-07 16:29
Sure give me 24h :)

**Closed** 2023-02-18 17:03 UTC
Labels: duplicate

**Comment by maddox** [comment] 2023-04-06 04:13
I've run into this issue as well, even on v41. I noticed when going to the controller tester in Steam that the Xbox button does not light up until you let go of the button. This explains why the work around works.

So it sounds like for some reason it's registering the button press on release, not press.

Just thought I'd mention this if it was something that could be controlled.

**Comment by rzippo** [comment] 2023-05-08 22:07
I have this issue as well, on the latest release. The workaround _sometimes_ works, but it's far from a fix.
