### ISSUE TITLE
ChimeraOS 42 does not boot, even after fresh install

### ISSUE THREAD

**Issue by SSchott** [ChimeraOS/chimeraos#619] opened 2023-05-15 20:18 UTC
The new release of ChimeraOS completely messed up my setup. It tries to boot up in desktop mode the first time, and gets stuck on a gray screen. Sometimes I manage to get into a tty, but none of the sessions boots up. In 41 only the old Big Picture mode was working properly.

As I know the boot/partition setup could affect, I formatted the drive and reinstalled, to the same result with a fresh install.

System specs:
GTX 1070 Ti
Ryzen 5 2600
ASRock Fatal1ty B450

**Comment by Northbane-arch** [comment] 2023-05-17 07:34
I too have this issue. Tried a fresh install on a "new" system some days ago, initially got stuck at "Downloading configuration updates" but got passed that but the screen went black/grey. 

Tried updating my ASUS gaming laptop from v39 to 42 but the same issue appeared there too after reboot. Cant use the system any longer.

Specs:
ASUS H270i
Intel i5 7400
GTX 1070
16GB RAM

Laptop:
Ryzen 3750H
16GB RAM
GTX 1650 Ti

**Comment by SSchott** [comment] 2023-05-20 13:20
I ended up installing Pop OS, and configuring Steam with GEProton and to boot straight into Big Picture. Seems to be more reliable until further notice...

**Comment by darkmasa** [comment] 2023-05-23 17:43
Have this same issue from February or March and can't install from new ISO. I move to Winesapos or other Linux.
check ChimeraOS Requirements

**Comment by darkmasa** [comment] 2023-05-24 06:28
> I too have this issue. Tried a fresh install on a "new" system some days ago, initially got stuck at "Downloading configuration updates" but got passed that but the screen went black/grey.
> 
>you must wait for ending process configuration updates, turn off display when screen flickering
>

**Comment by Northbane-arch** [comment] 2023-05-24 12:28
> > I too have this issue. Tried a fresh install on a "new" system some days ago, initially got stuck at "Downloading configuration updates" but got passed that but the screen went black/grey.
> > you must wait for ending process configuration updates, turn off display when screen flickering

I've waited for about 24hours without any results, so there must be something else going on there.

**Comment by darkmasa** [comment] 2023-05-24 13:12
> > > I too have this issue. Tried a fresh install on a "new" system some days ago, initially got stuck at "Downloading configuration updates" but got passed that but the screen went black/grey.
> > > you must wait for ending process configuration updates, turn off display when screen flickering
> 
> I've waited for about 24hours without any results, so there must be something else going on there.

you can use this:
https://github.com/ChimeraOS/install-media/releases/tag/2023-02-15_432f20f

**Comment by Northbane-arch** [comment] 2023-05-24 13:19
I’ll try that thank you, but I thought that it just downloads the current version of chimera, but that February iso worked for you at least? Also downloaded the pre release iso of v43 so I should have all the tools needed hopefully.

Skickat från min mobil
________________________________
Från: darkmasa ***@***.***>
Skickat: Wednesday, May 24, 2023 3:12:56 PM
Till: ChimeraOS/chimeraos ***@***.***>
Kopia: Northbane-arch ***@***.***>; Comment ***@***.***>
Ämne: Re: [ChimeraOS/chimeraos] ChimeraOS 42 does not boot, even after fresh install (Issue #619)


I too have this issue. Tried a fresh install on a "new" system some days ago, initially got stuck at "Downloading configuration updates" but got passed that but the screen went black/grey.
you must wait for ending process configuration updates, turn off display when screen flickering

I've waited for about 24hours without any results, so there must be something else going on there.

you can use this:
https://github.com/ChimeraOS/install-media/releases/tag/2023-02-15_432f20f

**Comment by darkmasa** [comment] 2023-05-24 14:44
> I’ll try that thank you, but I thought that it just downloads the current version of chimera, but that February iso worked for you at least? Also downloaded the pre release iso of v43 so I should have all the tools needed hopefully.

latest version not worked for me not have EFI have old
today Linux it's not free:(  garuda is good for gamer

**Comment by Northbane-arch** [comment] 2023-05-24 15:01
Yeah that is a shame. But my PC does meet the sys req though.

I have tried Garuda but I felt it was too bloated.


Den ons 24 maj 2023 16:45darkmasa ***@***.***> skrev:

**Comment by darkmasa** [comment] 2023-05-24 17:29
Garuda is have most of desktops. If you like Steamdeck desktop try Winesapos

**Comment by al12gamer** [comment] 2023-07-07 21:23
ChimeraOS 43 may have fixed the anomalies you were experiencing there. Also, make sure your BIOS is up to date, as that was the problem with my install.

**Comment by darkmasa** [comment] 2023-07-16 11:21
I have install on virtualbox for some oldest games
![20230716_130821](https://github.com/ChimeraOS/chimeraos/assets/75207123/f6ea0efb-1498-4903-b996-6cecd6dcae0c)
![20230716_130601](https://github.com/ChimeraOS/chimeraos/assets/75207123/8ad97f6a-b164-4d49-842b-85da70a63e50)

**Comment by Northbane-arch** [comment] 2023-07-16 11:55
Didn’t fix it I’m afraid, still present in latest build even when I choose nightly in installer the problem is there.

Skickat från min mobil
________________________________
Från: Alex ***@***.***>
Skickat: Friday, July 7, 2023 11:23:43 PM
Till: ChimeraOS/chimeraos ***@***.***>
Kopia: Northbane-arch ***@***.***>; Comment ***@***.***>
Ämne: Re: [ChimeraOS/chimeraos] ChimeraOS 42 does not boot, even after fresh install (Issue #619)


ChimeraOS 43 may have fixed the anomalies you were experiencing there. Also, make sure your BIOS is up to date, as that was the problem with my install.

**Comment by darkmasa** [comment] 2023-07-16 14:14
worked for me ChimeraOS 43

boot from chimeraos-2023.02.15-x86_64

install on second drive

if not work install on SSD and manually boot

first boot time wait some minutes if black screen

uff too hot today for work:)
![20230716_155853](https://github.com/ChimeraOS/chimeraos/assets/75207123/2b82d20f-5c0b-4db2-95a7-cd046a9a4c70)

**Comment by al12gamer** [comment] 2023-07-16 22:28
ChimeraOS, from what I can tell, is meant for installation on real hardware vs VMs. Glad to see things are working out on a fresh install.

**Comment by darkmasa** [comment] 2023-07-17 09:51
I regulary not use on VMs but only one way for today, fresh install on SSD not working for me, can install only from old ISO file.
"legacy/bios not supported" in descripcion I see

**Comment by Samsagax** [comment] 2023-07-25 11:26
Closing as it seems to be fixed

**Closed by Samsagax** 2023-07-25 11:26 UTC

**Comment by Northbane-arch** [comment] 2023-07-25 20:21
Still having issues. So not completed / fixed.

Skickat från min mobil
________________________________
Från: Joaquín Ignacio Aramendía ***@***.***>
Skickat: Tuesday, July 25, 2023 1:26:35 PM
Till: ChimeraOS/chimeraos ***@***.***>
Kopia: Northbane-arch ***@***.***>; Comment ***@***.***>
Ämne: Re: [ChimeraOS/chimeraos] ChimeraOS 42 does not boot, even after fresh install (Issue #619)


Closed #619<https://github.com/ChimeraOS/chimeraos/issues/619> as completed.

**Comment by darkmasa** [comment] 2024-06-16 09:19
Hello I have change my motherboard to MSI mobo and I can install, but after install I cant boot Chimera

**Comment by Northbane-arch** [comment] 2024-06-18 08:00
Probably due to requirement of AMD gpu I reckon.

Skickat från min mobil
________________________________
Från: darkmasa ***@***.***>
Skickat: Sunday, June 16, 2024 11:20:16 AM
Till: ChimeraOS/chimeraos ***@***.***>
Kopia: Northbane-arch ***@***.***>; Comment ***@***.***>
Ämne: Re: [ChimeraOS/chimeraos] ChimeraOS 42 does not boot, even after fresh install (Issue #619)


Hello I have change my motherboard to MSI mobo and I can install, but after install I cant boot Chimera
