### ISSUE TITLE
Gamepad UI and chimera web app don't sync

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#361] opened 2022-07-22 21:53 UTC
So I installed in bug picture mode some emulation roms from the chimera web app, but I wanted the steam so 3 feel suddenly

I went to terminal mode and got to the gamepad UI session mode, played a bit of games and wanted another game to emulate, but when I go to the IP of my Aya neo, it doesn't show password,

**Comment by pastaq** [comment] 2022-07-23 17:29
This will also be resolved in v34. For now there are a couple things you can do

- Switch back to BPM temporarily
- Log into the web UI using the BPM code
- under System, deselect "Generate a new password for each login" checkbox
- type in a password of your choice 2x in the boxes that appear
- scroll to the bottom and select save
- switch back to gamepadUI
Now you'll be able to put in the password you selected when you navigate to the webui.

**Comment by Sturmlocke86** [comment] 2022-07-24 08:14
> This will also be resolved in v34. For now there are a couple things you can do
> 
> * Switch back to BPM temporarily
> * Log into the web UI using the BPM code
> * under System, deselect "Generate a new password for each login" checkbox
> * type in a password of your choice 2x in the boxes that appear
> * scroll to the bottom and select save
> * switch back to gamepadUI
>   Now you'll be able to put in the password you selected when you navigate to the webui.

Thanks! Was researching this the other day bc I wasn't able to login to the webui via Deck mode.

**Comment by alkazar** [comment] 2022-07-26 11:37
Duplicate of #316

**Closed by alkazar** 2022-07-26 11:37 UTC
