### ISSUE TITLE
Can't Install ChimeraOS

### ISSUE THREAD

**Issue by Xenoxis** [ChimeraOS/chimeraos#242] opened 2021-07-03 10:15 UTC
Hello, i'm tying to install ChimeraOS using a usb key, but it's doing nothing after "Probing EDD (edd=off to disable) ... ok".

I'm using the latest ChimeraOS iso (2021-07-01), installed on the usb key using rufus 3.14 (using MB0 boot mode).
The computer which I try to install is a old one (using a BIOS only) on a AMD Phenom II x4 965, 8 Go of DDR2 RAM and a Nvidia GTX760.

Do you know why it doesn't boot up to the installation ?
Thanks

**Comment by Xenoxis** [comment] 2021-07-03 12:48
Works when disabling ACPI in BIOS, so there's a bug with ACPI ?

**Comment by Samsagax** [comment] 2021-07-03 15:24
> Works when disabling ACPI in BIOS, so there's a bug with ACPI ?

Might be an ACPI BIOS bug. It's not uncommon, specially with first revision Motherboards if the BIOS wasn't updated in a while. You could try that. But since you succeded in installing, could you try to enable ACPI again and see if it works?

**Comment by Samsagax** [comment] 2021-07-21 20:46
@Xenoxis have you succeeded in the installation? Have you tried the new install-media?

**Comment by Xenoxis** [comment] 2021-07-22 12:59
Yes I was able to install gamer-os by disabling ACPI and re-enabling it
after installation, thanks

**Comment by Samsagax** [comment] 2021-07-22 13:32
Thanks for the follow up @Xenoxis. Could you close the issue, please?
Great you could do it and happy gaming!

**Comment by Xenoxis** [comment] 2021-07-25 14:17
I think it's not good to close the issue while it isn't fixed yet.
Shouldn't we take a lot at where it failed and fix it ?

**Comment by Samsagax** [comment] 2021-07-25 14:36
Of course. But since the problem is ACPI and seems to be working now its likely a kernel version issue that sorted itself or a machine dependent issue. Both we don' t have control over and can't really do anything since we cannot reproduce it.

**Comment by chimera-os-fan** [comment] 2021-10-03 19:13
I just tried this today, so I'm adding it in case it's of use.  

You can disable edd by hitting TAB while the "install" option is highlighted, hit the spacebar once, then type "edd=off" (no quotes) and hit ENTER.  The installation may take a little bit, but it should continue.

**Closed** 2021-12-22 03:52 UTC
