### ISSUE TITLE
Black screen after clean install (intel/nvidia GeForce GTX 970M)

### ISSUE THREAD

**Issue by j-jeurissen** [ChimeraOS/chimeraos#524] opened 2023-02-27 17:55 UTC
I'm getting a black screen on boot. The system does boot up because I can get into a terminal. I don't have a user that I can use though. And I'm not familiar with arch linux though.

https://www.msi.com/Laptop/GS70-2QE-Stealth-Pro/Specification
chimeraos-2023.02.15-x86_64.iso

**Comment by FleischKarussel** [comment] 2023-03-14 14:40
Hello,

I'm having the same issue.

To login via web or via ssh (to set the key or use the same password) you need to see the login password on the screen.
Chicken/Egg issue :/

HP EliteDesk 800 G1
Intel 4590S with HD 4600

**Comment by FleischKarussel** [comment] 2023-03-14 14:48
This seems to be a dupe of #516

**Comment by j-jeurissen** [comment] 2023-03-14 14:57
yes, let's continue at #516?

**Closed** 2023-03-14 20:43 UTC
Labels: duplicate
