### ISSUE TITLE
Root password is not gamer

### ISSUE THREAD

**Issue by rfrayer420** [ChimeraOS/chimeraos#642] opened 2023-06-01 13:02 UTC
Am I missing something thinking that the root password was supposed to be gamer? I have reinstalled and redownloaded and cannot access root so that I might repair the bluetooth sleep issue. Ive attempted sudo, I have attempted both su and sudo su. Cant change the user password either for gamer.

**Comment by rfrayer420** [comment] 2023-06-01 13:05
with the dash? I have been trying without.

**Comment by npaladin2000** [comment] 2023-06-01 13:07
Not sure it matters on this, I use it on my RHEL servers because otherwise it switches the user to root but the session and environment variables from the regular user hang around. If it's not working without it, try it with it.  But it should work without it too I think. 

You're using "sudo su" and then entering "gamer" for the password? That really should be working.

**Comment by Samsagax** [comment] 2023-06-02 13:02
> Am I missing something thinking that the root password was supposed to be gamer? I have reinstalled and redownloaded and cannot access root so that I might repair the bluetooth sleep issue. Ive attempted sudo, I have attempted both su and sudo su. Cant change the user password either for gamer.

What are you trying to run?

**Comment by pastaq** [comment] 2023-06-02 13:48
> Am I missing something thinking that the root password was supposed to be gamer? I have reinstalled and redownloaded and cannot access root so that I might repair the bluetooth sleep issue. Ive attempted sudo, I have attempted both su and sudo su. Cant change the user password either for gamer.

This is an irregular occurance but we have seen it in the past. Typically a reboot will restore functionality. We haven't been able to identify a root cause (heh) yet but it is on our radar. After the reboot the sudo password will be `gamer`

**Comment by Samsagax** [comment] 2023-06-12 10:35
Closing as there is no answer

**Closed by Samsagax** 2023-06-12 10:35 UTC

**Comment by ruineka** [comment] 2023-06-12 11:31
> Closing as there is no answer

overlay bug?

**Comment by thanone2** [comment] 2023-11-08 23:12
had this same bug on recent installation

**Comment by nightttide** [comment] 2024-03-16 16:30
On a fresh installation there is no root password set. You will have to set it with `sudo passwd root`. Also be carefull setting the root password, you should probably set it to something other than gamer

**Comment by RastaTaz** [comment] 2025-07-20 15:44
Something is really weird here: I have a password issue when using "sudo su -" as gamer user but I was sure I type the good password...
As I found a redit thread mentioning  it may have something to do with language (indeed I changed language to french).
After many tries to be sure I was not mistyping the password, and as did't want to re-install ChimeraOS, I tried "LANG=EN sudo su -" and it worked first time !!

=> Can't explain or understand why but there sure is something related to system language here...
