### ISSUE TITLE
Chimera OS won't start from external HDD (Timed out waiting for device)

### ISSUE THREAD

**Issue by nslsrv** [ChimeraOS/chimeraos#347] opened 2022-06-13 22:24 UTC
Hi. After installation to external USB HDD Chimera OS won't start, being unable to mount EFI and root partitions.

I've reproduced this using two different machines, using both BIOS Legacy boot and UEFI boot. In every case at first screen is going clear black and then after some time the it dumps the following:

```
[ TIME ] Timed out waiting for device /dev/disk/by-label/frzr_efi.
[DEPEND] Dependency failed for /boot.
[ TIME ] Timed out waiting for device ??m/dev/disk/by-label/frzr_root.
[DEPEND] Dependency failed for /var.
[DEPEND] Dependency failed for Bluetooth service.
[DEPEND] Dependency failed for ...
...
[DEPEND] Dependency failed for /home.
You are in emergency mode. After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" or "exit"
to boot into default mode.

Cannot open access to console, the root account is locked.
See sulogin(8) man page for more details.

Press Enter to continue.
```

It seems like bootloader is doing its job, but either init ramdisk or the Chimera system itself are not able to detect the external drive during boot. At the same time installation to SATA-connected internal HDD produces working system without these issues. Intallation of Chimera OS to external HDD was successful.

After pressing Enter system does nothing helpful, there's no console or anything which would help to investigate the issue.

Chimera OS version: `chimeraos-33_7dcb575`
Install media version: `chimeraos-2022.06.02-x86_64.iso`
External drive: WD Elements, USB 3.0

**Comment by alkazar** [comment] 2022-06-14 02:52
This is due to a bug in the `steam-removable-media` package. The issue is already fixed in the latest upstream version of that package and will be included in the next release of ChimeraOS.

**Comment by pastaq** [comment] 2022-06-18 00:12
You can manually deploy an older version of the software until the next release. If you have access to frzr-deploy in the degraded state simply follow the commands in https://github.com/ChimeraOS/chimeraos/wiki/Development#contributing for deploying an older version.

If that isn't possible, stopping the installer and changing the install script is the best way. 
- Boot the USB install media with no internet connectivity (ethernet disconnected, don't connect to wifi).
- Quit the installer.
- type `nano install.sh`
- Go down to the line that says `ffrzr-deploy chimeraos/chimeraos:stable` and change it to `frzr-deploy chimeraos/chimeraos:32`
- Close nano with `ctrl+x`, hit `y` to save
- Reconnect ethernet cable if used. If using WiFi, follow the next command and use the installer WiFi configurator.
- run `./install.sh`

Once v34 is released you can run `frzr-deploy chimeraos/chimeraos:stable` and it will keep you on the stable version going forward.

**Comment by alkazar** [comment] 2022-08-09 22:05
Fixed in latest release.

**Closed by alkazar** 2022-08-09 22:05 UTC
