### ISSUE TITLE
No Audio or touchscreen on GPD WIn 3

### ISSUE THREAD

**Issue by Smashman4** [ChimeraOS/chimeraos#269] opened 2021-09-27 22:28 UTC
Hello,

Loving this OS, but there is no audio or touchscreen when using it on my GPD WIn 3. 
According to the Arch Linux Wiki, There is a a workaround for these issues, but I don't know how to apply it to ChimeraOS.
https://wiki.archlinux.org/title/GPD_Win_3

Appreciate any help I can get.

**Comment by Samsagax** [comment] 2021-09-27 22:48
For the audio part you will need to enter a TTY or SSH into your machine then create the file `/etc/modprobe.d/alsa-base.conf`:

`$ sudo nano /etc/modprobe.d/alsa-base.conf`

Then add this line:

`options snd-hda-intel dmic_detect=0`

Save and exit. The reboot your machine.

**Comment by Smashman4** [comment] 2021-09-28 00:29
> For the audio part you will need to enter a TTY or SSH (user and password is gamer/gamer) into your machine then create the file `/etc/modprobe.d/alsa-base.conf`:
> 
> `$ sudo nano /etc/modprobe.d/alsa-base.conf`
> 
> Then add this line:
> 
> `options snd-hda-intel dmic_detect=0`
> 
> Save and exit. The reboot your machine.
> 
> For the touchscreen follow the same procedure to edit the relevant file as directed on the wiki.

Thank you so much. That fixed the sound, but I can't install the goodix touch drivers for some reason. Do I need to add a repository (https://aur.archlinux.org/packages/goodix-gpdwin3-dkms/), or am I using the command to install it incorrectly?

**Comment by Samsagax** [comment] 2021-09-28 15:11
The filesystem in ChimeraOS is read only by design, no package install is possible outside of some tests (frzr will overwrite any changes you make and breakage is possible) so you have to use the alternative solution by editing the relevant Xorg configuration.

**Comment by Smashman4** [comment] 2021-09-28 21:45
Ok. seems like it's a hassle to do that, so I won't.

One last thing. I don't know if I should start a new issue for this, but I was able to mount my sd card to ChomeraOS, but how do I add it to the list of steam library folders?

**Comment by alkazar** [comment] 2021-09-29 00:20
Steam Big Picture does not support adding or managing Steam library folders.

There is an open ticket for a workaround here: https://github.com/ChimeraOS/chimeraos/issues/224

However, since it appears from Steam Deck screenshots that Valve is adding this feature to the gamepad UI (the new Steam Deck UI that is supposed to replace Big Picture), this work has been dropped.

**Comment by Smashman4** [comment] 2021-10-02 00:21
> Steam Big Picture does not support adding or managing Steam library folders.
> 
> There is an open ticket for a workaround here: #224
> 
> However, since it appears from Steam Deck screenshots that Valve is adding this feature to the gamepad UI (the new Steam Deck UI that is supposed to replace Big Picture), this work has been dropped.

Ok. Then I'll wait to see that get implemented into chimera. The last thing I was to do with the Win 3 is be able to record via hdmi capture card. Not sure how I can do that cause the win 3 display will show fine, but the capture card display will be blank. I can probably fix the audio not working on the capture card myself though.

**Comment by Samsagax** [comment] 2022-12-27 11:55
Closing as the original (and also the follow up) issue is resolved.

**Closed by Samsagax** 2022-12-27 11:55 UTC
