### ISSUE TITLE
Feature Request : Add controls of emulator's parameters

### ISSUE THREAD

**Issue by Xenoxis** [ChimeraOS/chimeraos#198] opened 2021-02-15 10:32 UTC
Currently, we can't modify any parameters from any emulators. It will be great if we can modify resolutions, video filters, controls, languages, etc ...

This will can be done from the web interface, but personally i prefer if this feature can be integrated from controls directly in game.

**Comment by sharkwouter** [comment] 2021-02-15 10:48
Thanks for the report. This is a nice idea. Not sure how to implement it, though, but good to keep in mind.

**Comment by Xenoxis** [comment] 2021-02-15 15:18
I can take a look, i'm really interested in how gameros works, particularly about steam buddy.

**Comment by mrbigmouth502** [comment] 2021-07-09 13:29
Count me interested as well. I'd love to be able to do things like use scanline shaders.

**Comment by alkazar** [comment] 2022-08-10 02:25
Duplicate of chimeraos/chimera#88

**Closed by alkazar** 2022-08-10 02:25 UTC
